In [1]:
import numpy as np
import random

In [2]:
onet=[-1,1]

In [3]:
sum=0
nsum=0
x=0

In [4]:
n = int(input('введите число больше 2: '))

введите число больше 2: 3


In [5]:
matrix=np.zeros((n,n))

In [6]:
for i in range(n):
    for j in range(n):
        matrix[i,j]=random.choice(onet)
print(matrix)

[[-1. -1.  1.]
 [-1.  1.  1.]
 [-1. -1. -1.]]


In [9]:
for i in range(n):
    for j in range(n):
        nsum+=matrix[i,j]*matrix[i,j-1]
        x+=matrix[i-1,j]*matrix[i,j]
        
sum=nsum+x
print(sum)

6.0
